### ISSUE TITLE
Mask annotations are not available

### ISSUE THREAD

**Issue by naziaperwaiz** [Dingyuan-Zheng/maskPS#1]
The shares links for mask annotations for both datasets PRW and CUHK-SYSU are not working.
Can you please share the working links?
Many thanks.

**Comment by Dingyuan-Zheng** [comment]
The link might not work in your region.
Anyway, I've updated README. You can download the annotation files from google drive now.

**Comment by naziaperwaiz** [comment]
I really appreciate your quick response.
